dist: trusty
sudo: required
language: generic
services:
- docker
addons:
  sonarcloud:
    organization: "3r1co-github"
env:
  global:
    - DOCKER_IMAGE_NAME="3r1co/registry-ui:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER"
    - SONAR_EXCLUSIONS="frontend/node_modules/**,frontend/coverage/lcov-report/**,**/*.test.js,coverage.xml,**/*_test.go"
    - SONAR_NODE_COVERAGE="frontend/coverage/lcov.info"
    - SONAR_GO_COVERAGE="coverage.out"
cache:
  - pip
  - npm
before_install:
  - pyenv global 3.6.3
  - nvm install node
  - gimme stable
  - cd frontend
  - npm install -s
install:
  - npm test -- --coverage
  - cd ..
  - go test -json > report.json
  - go test -coverprofile=coverage.out
script:
  - sonar-scanner -Dsonar.projectKey=3r1co_registry-frontend -Dsonar.sources=. -Dsonar.exclusions=$SONAR_EXCLUSIONS -Dsonar.javascript.lcov.reportPaths=$SONAR_NODE_COVERAGE -Dsonar.go.coverage.reportPaths=$SONAR_GO_COVERAGE
after_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $DOCKER_IMAGE_NAME .
  - docker push $DOCKER_IMAGE_NAME