language: python
python:
  - "3.6"
sudo: required
services:
- docker
addons:
  ssh_known_hosts: 46.101.222.96
cache: pip
install:
  - echo "Skipping local pip, do build in Docker"
script:
  - echo "Success"
env:
- DOCKER_IMAGE_NAME="3r1co/registry-ui:$TRAVIS_BUILD_NUMBER"
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t $DOCKER_IMAGE_NAME .
- docker push $DOCKER_IMAGE_NAME