version: '3'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    command: --registry ${DOCKER_REGISTRY} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD} --cacert ${DOCKER_CA}
    volumes:
     - ./ca.crt:/tmp/ca.crt
    environment:
     - REDIS_HOST=${REDIS_HOST}
     - LOGLEVEL=debug
  redis:
    image: "redislabs/rejson:latest"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
  redis-commander:
    image: "rediscommander/redis-commander"
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
  registry:
    image: "registry:2"
    ports:
      - "5000:5000"
volumes:
  redis-data: